// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPzd__wx-jGJ-5fmxnZPeQEkjg8x7tres',
    appId: '1:925243261803:web:bb856d31e18f72048fc22e',
    messagingSenderId: '925243261803',
    projectId: 'platerecognitionsd',
    authDomain: 'platerecognitionsd.firebaseapp.com',
    databaseURL: 'https://platerecognitionsd-default-rtdb.firebaseio.com',
    storageBucket: 'platerecognitionsd.appspot.com',
    measurementId: 'G-XLMN6E1MN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTDfD35AHyv9oIE8hKVnCMiI9CDo6LTDQ',
    appId: '1:925243261803:android:e2a88e21b25cec448fc22e',
    messagingSenderId: '925243261803',
    projectId: 'platerecognitionsd',
    databaseURL: 'https://platerecognitionsd-default-rtdb.firebaseio.com',
    storageBucket: 'platerecognitionsd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvSOrq3umHhlJpK43O9Cj4kGXzcCBkqm4',
    appId: '1:925243261803:ios:aecfc574aea8a94b8fc22e',
    messagingSenderId: '925243261803',
    projectId: 'platerecognitionsd',
    databaseURL: 'https://platerecognitionsd-default-rtdb.firebaseio.com',
    storageBucket: 'platerecognitionsd.appspot.com',
    iosClientId: '925243261803-277mhb70iok8rjltaugdfouc3a8kgalp.apps.googleusercontent.com',
    iosBundleId: 'com.example.leitorPlacas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvSOrq3umHhlJpK43O9Cj4kGXzcCBkqm4',
    appId: '1:925243261803:ios:aecfc574aea8a94b8fc22e',
    messagingSenderId: '925243261803',
    projectId: 'platerecognitionsd',
    databaseURL: 'https://platerecognitionsd-default-rtdb.firebaseio.com',
    storageBucket: 'platerecognitionsd.appspot.com',
    iosClientId: '925243261803-277mhb70iok8rjltaugdfouc3a8kgalp.apps.googleusercontent.com',
    iosBundleId: 'com.example.leitorPlacas',
  );
}
